name: Build Quik v4.0.11

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (with tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     # fetch full history
          fetch-tags: true   # ensure tags are fetched
          ref: v4.0.11

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Build debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: quik-v4.0.11-apk
          path: |
            **/build/outputs/apk/**/*.apk
